# keep younger server properties
server:
  port: 11000
  servlet:
    context-path: /ky
  session:
    cookie:
      name: KY_AUTH
spring:
  application:
    name: keep-younger-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keep_younger?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dayi.entity
  configuration:
    # can get id while saving data
    use-generated-keys: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
